# Generated by Django 3.2.12 on 2023-05-31 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
